name: Release me


run-name: "${{ inputs.formula }} | ${{ inputs.version }}"

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      formula:
        required: true
        type: string
        description: |
          The formula to release. Must be one of the following:
          - `sbx`
          - `rv`
          - `protopkg`

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1.7.0
        id: generate-token
        with:
          app-id: ${{ secrets.CONDUCTOR_APP_ID }}
          private-key: ${{ secrets.CONDUCTOR_PRIVATE_KEY }}
          repositories: homebrew-reverb
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.generate-token.outputs.token }}
          repository: reverbdotcom/homebrew-reverb
      - name: Release
        env:
          VERSION: ${{ inputs.version }}
          FORMULA: ${{ inputs.formula }}
        run: |
          git config user.name "conductor[bot]"
          git config user.email "810454+conductor[bot]@users.noreply.github.com"

          echo "Releasing $FORMULA version $VERSION"
          VERSION=$VERSION make $FORMULA-release

